Repository Central-MakeUs/PreviewInsure-Web, pull requests merged in 2024-08, with the labels that each got.

#22 ✨ Feat: 실패알람 추가 및 약관페이지 디테일추가
  src/assets/icons/Warning.svg
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/LoginAndRegister/Agree.tsx
  src/components/commons/FailAlarm.tsx
  src/components/commons/Selector.tsx
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/screens/LoginAndRegister/RegisterAgree.tsx
  src/styles/theme.ts
  src/types/LoginAndRegisterComponents.ts
  src/types/commonComponents.ts
Labels: enhancement

#25 ✨ Feat: QNA화면
  package-lock.json
  package.json
  src/apis/question/question.ts
  src/assets/icons/Insue/Accident.svg
  src/assets/icons/Insue/CI.svg
  src/assets/icons/Insue/Dental.svg
  src/assets/icons/Insue/Driver.svg
  src/assets/icons/Insue/Education.svg
  src/assets/icons/Insue/Health.svg
  src/assets/icons/Insue/Life.svg
  src/assets/icons/Insue/NursingCare.svg
  src/assets/icons/Insue/Pension.svg
  src/assets/icons/Insue/Pet.svg
  src/assets/icons/Insue/Saving.svg
  src/assets/imgs/qna-background.png
  src/components/Question/CategoryItem.tsx
  src/components/Question/QuestionAnswer.tsx
  src/components/commons/Footer.tsx
  src/main.tsx
  src/screens/Question/Question.tsx
  src/screens/homeScreen.tsx
  src/styles/theme.ts
  src/types/QuestionComponents.ts
  src/utils/common/InsurCategory.ts
Labels: enhancement

#27 Feature/insue boarding
  package-lock.json
  package.json
  src/assets/icons/Approve.svg
  src/assets/icons/DownSelector.svg
  src/assets/icons/InsueCard/Book.svg
  src/assets/icons/InsueCard/CI.svg
  src/assets/icons/InsueCard/Car.svg
  src/assets/icons/InsueCard/Health.svg
  src/assets/icons/InsueCard/HeartBeat.svg
  src/assets/icons/InsueCard/HospitalSign.svg
  src/assets/icons/InsueCard/MoneyBag.svg
  src/assets/icons/InsueCard/PetFootprint.svg
  src/assets/icons/InsueCard/PiggyBank.svg
  src/assets/icons/InsueCard/ToothBraces.svg
  src/assets/icons/InsueCard/WheelChair.svg
  src/assets/icons/PartyPopper.svg
  src/assets/icons/UpSelector.svg
  src/components/InsueBoarding/Complete.tsx
  src/components/InsueBoarding/Congraulate.tsx
  src/components/InsueBoarding/InsueBoardingCompononets/MonthPicker.tsx
  src/components/InsueBoarding/InsueBoardingCompononets/YearPicker.tsx
  src/components/InsueBoarding/Step1.tsx
  src/components/InsueBoarding/Step2.tsx
  src/components/InsueBoarding/Step3.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/InsureCard.tsx
  src/components/commons/Process2.tsx
  src/components/commons/rootRouter.tsx
  src/screens/InsueBording/InsueBordingScreen.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/screens/testScreen2.tsx
  src/types/commonComponents.ts
Labels: enhancement

#29 ✨ Feat: 인슈플래너 답변 화면 구현
  package-lock.json
  package.json
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx
  src/components/InsuePlanner/InsuePlannerComponents/QuestionBox.tsx
  src/components/InsuePlanner/InsuePlannerLoading.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/commons/SearchBar.tsx
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/screens/testScreen2.tsx
  src/types/InsuePlannerComponents.ts
  src/types/commonComponents.ts
Labels: enhancement

#31 ✨ Feat: main screen
  src/assets/icons/Right.svg
  src/assets/icons/RightMini.svg
  src/assets/imgs/logo-white.webp
  src/assets/imgs/main-character.webp
  src/components/Main/InsueDetailIcon.tsx
  src/components/Main/InsueMainIcon.tsx
  src/components/commons/GradientBackground.tsx
  src/components/commons/Header.tsx
  src/screens/Main/MainScreen.tsx
  src/types/MainComponents.ts
  src/utils/common/InsurCategory.ts
Labels: enhancement

#33 ✨ Feat: 인슈플래너 질문페이지 수정
  src/components/InsuePlanner/InsuePlannerComponents/InsueQuestionCategory.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/components/commons/InsureCard.tsx
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/static/insures.ts
  src/types/InsuePlannerComponents.ts
Labels: enhancement

#37 ✨ Feat: 인슈보딩 UI 수정 및 API 연동
  src/apis/insueboarding/insueboarding.ts
  src/components/InsueBoarding/Complete.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/InsureCard.tsx
  src/main.tsx
  src/utils/axios.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#38 ✨ Feat: 네비게이션바
  src/components/commons/Header.tsx
  src/screens/Main/MainScreen.tsx
Labels: enhancement

#41 ✨ Feat: 모바일 Bottom Navigation 추가
  package-lock.json
  package.json
  src/assets/icons/BottomNav/Home.svg
  src/assets/icons/BottomNav/InsuePlanner.svg
  src/assets/icons/BottomNav/MyInsue.svg
  src/assets/icons/BottomNav/QNA.svg
  src/assets/icons/BottomNav/User.svg
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/BottomNav.tsx
  src/components/commons/Footer.tsx
  src/components/commons/rootRouter.tsx
Labels: enhancement

#45 🐛 Fix: apple OAuth 방식변경
  src/screens/LoginAndRegister/AppleLoginCallback.tsx
  src/utils/LoginAndRegister/AppleLogin.ts
Labels: enhancement

#47 ✨ Feat: 홈, QNA 화면 모바일 반응형 적용
  src/components/Main/InsueMainIcon.tsx
  src/components/Question/CategoryItem.tsx
  src/components/Question/QuestionAnswer.tsx
  src/components/commons/Header.tsx
  src/screens/Main/MainScreen.tsx
  src/screens/Question/Question.tsx
Labels: enhancement

#48 💄 Design: 인슈보딩 모바일
  src/components/InsueBoarding/Step2.tsx
  src/components/InsueBoarding/Step3.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/InsureCard.tsx
  src/screens/LoginAndRegister/LoginScreen.tsx
  src/screens/LoginAndRegister/RegisterAgree.tsx
  src/screens/LoginAndRegister/RegisterScreen.tsx
  src/static/insurebordCards.tsx
Labels: enhancement

#50 Design/insueplanner mobile
  src/assets/icons/InsuePlanner/Airplane.svg
  src/components/InsueBoarding/Congraulate.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/InsueQuestionCategory.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/components/commons/InsureCard.tsx
Labels: enhancement

#51 💄 Design: 홈화면 캐릭터 이미지 위치, QNA 상세보기 svg 수정
  src/components/Question/QuestionAnswer.tsx
  src/screens/Main/MainScreen.tsx
Labels: enhancement

#54 ✨ Feat: insueMap Mobile화면
  src/components/InsueMap/InsueDetailIcon.tsx
  src/components/InsueMap/InsueMapHeadSection.tsx
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/commons/GradientBackground.tsx
  src/screens/InsueMap/InsueMapScreen.tsx
Labels: enhancement

#55 💄 Design: Favicon 설정
  index.html
  public/presue.ico
  public/vite.svg
Labels: enhancement

#58 ✨ Feat: 인슈보딩 및 회원가입 디테일
  src/apis/insueboarding/insueboarding.d.ts
  src/apis/insueboarding/insueboarding.keys.ts
  src/apis/insueboarding/insueboarding.ts
  src/assets/icons/DownArrowRight.svg
  src/components/InsueBoarding/Complete.tsx
  src/components/InsueBoarding/Step2.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/GradientBackground.tsx
  src/components/commons/InsureCard.tsx
  src/screens/InsueBording/InsueBordingScreen.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/types/commonComponents.ts
Labels: enhancement

#61 ✨ Feat: policy 화면
  src/components/commons/Footer.tsx
  src/components/commons/rootRouter.tsx
  src/screens/Main/PolicyPrivacyScreen.tsx
  src/screens/Main/PolicyServiceScreen.tsx
Labels: enhancement

#64 Feat/insue planner api
  src/apis/insuePlanner/insuePlanner.d.ts
  src/apis/insuePlanner/insuePlanner.keys.ts
  src/apis/insuePlanner/insuePlanner.ts
  src/apis/register/register.ts
  src/components/InsueBoarding/Complete.tsx
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/types/InsuePlannerComponents.ts
  src/utils/axios.ts
Labels: enhancement

#67 🐛 Fix: isLogin 값 체크하도록 수정
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/stores/useStore.ts
Labels: enhancement

#68 🐛 Fix: Head에서 마이페이지 이동하도록 수정
  src/components/commons/Header.tsx
Labels: enhancement

#69 ✨ Feat: 인슈플래너 답변 모바일
  package-lock.json
  package.json
  src/assets/icons/InsuePlanner/Menu.svg
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryListContainer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/InsuePlannerAnswerMobileModal.tsx
  src/components/InsuePlanner/InsuePlannerComponents/QuestionBox.tsx
  src/reset.css
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/styles/media.ts
  src/types/InsuePlannerComponents.ts
Labels: enhancement

#71 ✨ Feat: 회원가입 약관동의 문구 적용
  src/components/LoginAndRegister/Agree.tsx
  src/screens/LoginAndRegister/RegisterAgree.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/screens/Main/PolicyPrivacyScreen.tsx
  src/screens/Main/PolicyServiceScreen.tsx
Labels: enhancement

#72 ✨ Feat: inseuMap API 연동
  src/apis/insuemap/insuemap.d.ts
  src/apis/insuemap/insuemap.ts
  src/components/InsueMap/InsueDetailIcon.tsx
  src/components/InsueMap/InsueMapHeadSection.tsx
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/InsueMap/RecommendItem.tsx
  src/components/InsueMap/RecommendSection.tsx
  src/components/commons/Header.tsx
  src/screens/InsueMap/InsueMapScreen.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/stores/useStore.ts
  src/types/InsueMapComponents.ts
  src/utils/common/InsurCategory.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#73 Feature/qna api
  src/apis/question/question.d.ts
  src/apis/question/question.ts
  src/assets/imgs/qna-background.png
  src/components/Question/QuestionAnswer.tsx
  src/screens/Question/Question.tsx
  src/types/QuestionComponents.ts
Labels: enhancement

#75 Fix : bottomnav
  src/apis/insuemap/insuemap.d.ts
  src/apis/insuemap/insuemap.ts
  src/apis/question/question.d.ts
  src/apis/question/question.ts
  src/assets/icons/BottomNav/Home.svg
  src/assets/icons/BottomNav/InsuePlanner.svg
  src/assets/icons/BottomNav/MyInsue.svg
  src/assets/icons/BottomNav/QNA.svg
  src/assets/icons/BottomNav/User.svg
  src/assets/imgs/qna-background.png
  src/components/InsueMap/InsueDetailIcon.tsx
  src/components/InsueMap/InsueMapHeadSection.tsx
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/InsueMap/RecommendItem.tsx
  src/components/InsueMap/RecommendSection.tsx
  src/components/Question/QuestionAnswer.tsx
  src/components/commons/BottomNav.tsx
  src/components/commons/Header.tsx
  src/components/commons/rootRouter.tsx
  src/screens/InsueMap/InsueMapScreen.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/screens/Question/Question.tsx
  src/stores/useStore.ts
  src/types/InsueMapComponents.ts
  src/types/QuestionComponents.ts
  src/utils/common/InsurCategory.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#76 💄 Design: 인슈 맵 관심보험 저장 버튼 css
  src/components/InsueMap/InsueMapHeadSection.tsx
Labels: enhancement

#77 design : webview ios
  src/components/InsueBoarding/Step4.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/LoginAndRegister/OAuthButton.tsx
  src/components/commons/InsureCard.tsx
  src/components/commons/Selector.tsx
Labels: enhancement

#79 ✨ Feat: myInsue 화면
  src/components/User/InsueBarItem.tsx
  src/components/commons/rootRouter.tsx
  src/screens/User/MyInsueScreen.tsx
Labels: enhancement

#81 🐛 Fix: IOS main 화면 이미지 랜더링 오류 수정 확인
  src/screens/Main/MainScreen.tsx
Labels: enhancement

#83 feat : 애플로그인 연결
  src/apis/insuePlanner/insuePlanner.ts
  src/apis/insueboarding/insueboarding.ts
  src/apis/register/register.d.ts
  src/apis/register/register.keys.ts
  src/apis/register/register.ts
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/commons/FailAlarm.tsx
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/screens/LoginAndRegister/AppleLoginCallback.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/stores/useStore.ts
  src/utils/axios.ts
Labels: enhancement

#85 ✨ Feat: 모바일 마이페이지 화면 추가
  src/assets/icons/Pencle.svg
  src/components/User/InfoSection.tsx
  src/components/User/InsueBarItem.tsx
  src/components/User/InsueSection.tsx
  src/screens/User/MyInsueScreen.tsx
  src/screens/User/UserInfoScreen.tsx
Labels: enhancement

#86 ✨ Feat: 인슈 맵 카테고리별 멘트 추가
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/InsueMap/RecommendSection.tsx
  src/screens/InsueMap/InsueMapScreen.tsx
  src/types/InsueMapComponents.ts
  src/utils/common/InsurCategory.ts
Labels: enhancement

#87 💄 Design: 인슈보딩 bottomnav 없앰. top 맞춤
  src/components/InsueBoarding/Step5.tsx
  src/components/commons/BottomNav.tsx
  src/screens/InsueBording/InsueBordingScreen.tsx
Labels: enhancement

#88 ✨ Feat: 로그인 토큰 연결
  package-lock.json
  package.json
  src/apis/account/account.ts
  src/apis/insuemap/insuemap.ts
  src/apis/question/question.ts
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/LoginAndRegister/Agree.tsx
  src/components/LoginAndRegister/registerContent.ts
  src/screens/InsuePlanner/InsuePlannerScreen.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/screens/LoginAndRegister/RegisterAgree.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/screens/Main/PolicyPrivacyScreen.tsx
  src/screens/User/UserInfoScreen.tsx
Labels: enhancement

#90 💄 Design : 디자인 디버깅 수정
  src/components/InsueMap/InsueMapHeadSection.tsx
  src/components/commons/BottomNav.tsx
  src/screens/InsueMap/InsueMapScreen.tsx
  src/screens/LoginAndRegister/LoginScreen.tsx
Labels: enhancement

#91 feat : 배포전 디테일 수정
  src/components/InsueBoarding/Congraulate.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/User/InfoSection.tsx
  src/components/commons/FailAlarm.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
Labels: enhancement

#92 ✨ Feat: 마이페이지 API 연결
  src/apis/account/account.d.ts
  src/apis/account/account.ts
  src/components/User/InfoSection.tsx
  src/screens/Main/PolicyPrivacyScreen.tsx
  src/screens/Main/PolicyServiceScreen.tsx
  src/screens/User/UserInfoScreen.tsx
Labels: enhancement

#93 Feat/my insue api
  src/apis/account/account.d.ts
  src/apis/account/account.ts
  src/components/User/InfoSection.tsx
  src/components/User/InsueBarItem.tsx
  src/components/User/InsueSection.tsx
  src/utils/common/InsurCategory.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#94 🐛 Fix: 내보험 클릭 수정
  src/components/User/InsueBarItem.tsx
Labels: enhancement

#96 feat : zustand Persist 적용
  src/stores/useStore.ts
Labels: enhancement

#97 🐛 Fix: 인슈 맵 추천 막기
  src/components/InsueMap/RecommendSection.tsx
Labels: enhancement

#98 💄 Design: 회원가입 약관 글자크기
  src/components/LoginAndRegister/Agree.tsx
  src/components/LoginAndRegister/registerContent.ts
Labels: enhancement

#100 💄 Design: 인슈 맵 보험사 이동 버튼 숨김
  src/components/InsueMap/InsueMapSecondSection.tsx
Labels: enhancement

#102 ✨ Feat: QNA에서 가입한보험보기 API
  src/components/InsueMap/RecommendSection.tsx
  src/screens/Question/Question.tsx
  src/utils/common/InsurCategory.ts
Labels: enhancement

#104 🐛 Fix: ios UI 오류
  src/App.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/commons/Selector.tsx
  src/stores/useStore.ts
Labels: enhancement

#106 Fix/quickfix
  src/components/InsueBoarding/Complete.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/components/commons/BottomNav.tsx
  src/components/commons/rootRouter.tsx
  src/screens/LoginAndRegister/RegisterScreen.tsx
  src/styles/GlobalStyles.ts
  src/styles/media.ts
  src/types/InsuePlannerComponents.ts
Labels: bug

#107 🐛 Fix: 애견보험 수정
  src/utils/common/InsurCategory.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#110 ✨ Feat: Footer 내용 변경
  src/assets/imgs/logo-gray.webp
  src/components/commons/Footer.tsx
Labels: enhancement

#111 Feat/insue map
  src/assets/icons/InsueMap/Map.svg
  src/assets/icons/InsueMap/MapLine.svg
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueMap2/Map.tsx
  src/components/commons/Selector.tsx
  src/components/commons/rootRouter.tsx
  src/screens/InsueMap2/InsueMap2Screen.tsx
Labels: enhancement

#112 🐛 Fix: 추천 테이블 head
  src/components/InsueMap/RecommendItem.tsx
  src/components/InsueMap/RecommendSection.tsx
Labels: enhancement

#113 🐛 Fix: 인슈맵 api 호출 수정
  src/components/InsueMap2/Map.tsx
Labels: enhancement

#114 💄 Design: head color
  src/components/commons/Header.tsx
Labels: enhancement

#116 🐛 Fix: QNA페이지 보유보험 > 관심보험 수정
  src/screens/Question/Question.tsx
Labels: enhancement

#117 ✨ Feat: 마이페이지 보험수 추가
  src/components/User/CountSection.tsx
  src/components/User/InfoSection.tsx
  src/components/User/InsueSection.tsx
  src/components/commons/rootRouter.tsx
  src/screens/User/RegistInsueScreen.tsx
  src/screens/User/UserInfoScreen.tsx
Labels: enhancement

#118 Fix/detail change
  src/assets/icons/InsuePlanner/SearchingForContent.svg
  src/components/InsueBoarding/Complete.tsx
  src/components/InsueBoarding/Congraulate.tsx
  src/components/InsueBoarding/InsueBoardingCompononets/MonthPicker.tsx
  src/components/InsueBoarding/Step1.tsx
  src/components/InsueBoarding/Step2.tsx
  src/components/InsueBoarding/Step3.tsx
  src/components/InsueBoarding/Step4.tsx
  src/components/InsueBoarding/Step5.tsx
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx
  src/components/InsuePlanner/InsuePlannerComponents/InsuePlannerAnswerMobileModal.tsx
  src/components/InsuePlanner/InsuePlannerComponents/InsueQuestionCategory.tsx
  src/components/InsuePlanner/InsuePlannerComponents/QuestionBox.tsx
  src/components/InsuePlanner/InsuePlannerLoading.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/components/LoginAndRegister/Agree.tsx
  src/components/LoginAndRegister/OAuthButton.tsx
  src/components/commons/InsureCard.tsx
  src/screens/InsueBording/InsueBordingScreen.tsx
  src/screens/LoginAndRegister/LoginScreen.tsx
  src/screens/LoginAndRegister/RegisterAgree.tsx
  src/screens/LoginAndRegister/RegisterNickname.tsx
  src/screens/LoginAndRegister/RegisterScreen.tsx
Labels: enhancement

#119 💄 Design: 인슈플래너 글자크기 조정
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
Labels: enhancement

#127 🐛 Fix: 메인 스와이퍼 회전
  src/screens/Main/MainScreen.tsx
Labels: enhancement

#128 🐛 Fix: googleLogin Popup 설정
  src/utils/LoginAndRegister/Login.ts
Labels: bug, enhancement

#130 Fix/detail change
  src/components/InsueMap/InsueDetailIcon.tsx
  src/components/InsueMap/InsueMapHeadSection.tsx
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/InsueMap/RecommendItem.tsx
  src/components/InsuePlanner/InsuePlannerAnswer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryItem.tsx
  src/components/InsuePlanner/InsuePlannerComponents/HistoryListContainer.tsx
  src/components/InsuePlanner/InsuePlannerComponents/InsueQuestionCategory.tsx
  src/components/InsuePlanner/InsuePlannerQuestion.tsx
  src/components/InsuePlanner/QuestionBox.tsx
  src/components/LoginAndRegister/OAuthButton.tsx
  src/components/commons/BottomNav.tsx
  src/components/commons/Header.tsx
  src/screens/LoginAndRegister/LoginScreen.tsx
  src/screens/LoginAndRegister/RegisterScreen.tsx
  src/screens/Main/MainScreen.tsx
  src/static/insures.ts
  src/utils/common/convertInsureType.ts
Labels: enhancement

#131 💄 Design: 디자인 수정
  src/components/Question/CategoryItem.tsx
  src/components/Question/QuestionAnswer.tsx
  src/components/User/InsueSection.tsx
  src/screens/Question/Question.tsx
  src/screens/User/RegistInsueScreen.tsx
  src/screens/User/UserInfoScreen.tsx
  src/utils/LoginAndRegister/Login.ts
Labels: bug

#133 💄 Design: QNA, Main, Header 디자인
  src/components/Question/QuestionAnswer.tsx
  src/components/commons/Header.tsx
  src/screens/Main/MainScreen.tsx
Labels: bug

#136 💄 Design: 이용약관 버튼 추가
  src/screens/Main/MainScreen.tsx
Labels: enhancement

#137 Fix/api return fix
  src/components/InsueMap/InsueDetailIcon.tsx
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/screens/User/UserInfoScreen.tsx
Labels: enhancement

#138 ✨ Feat: 새탭열기 Test
  src/screens/Main/MainScreen.tsx
  src/utils/common/openNewTab.ts
  src/vite-env.d.ts
Labels: enhancement

#139 🐛 Fix: 새탭 열기 설정
  src/components/InsueMap/InsueMapSecondSection.tsx
  src/components/InsueMap/RecommendItem.tsx
  src/components/InsuePlanner/InsuePlannerComponents/AnswerBox.tsx
  src/components/Question/QuestionAnswer.tsx
  src/screens/Main/MainScreen.tsx
  src/screens/User/UserInfoScreen.tsx
  src/utils/common/openNewTab.ts
Labels: enhancement

#144 ✨ Feat: 가입한 보험 수정 API 연동
  src/apis/account/account.d.ts
  src/apis/account/account.keys.ts
  src/apis/account/account.ts
  src/components/User/InsueBarItem.tsx
  src/components/User/InsueSection.tsx
Labels: enhancement

#145 🐛 Fix: 로그인 새창띄우기 수정
  src/screens/LoginAndRegister/AppleErrorCallback.tsx
  src/screens/LoginAndRegister/AppleLoginCallback.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/utils/LoginAndRegister/AppleLogin.ts
  src/utils/LoginAndRegister/Login.ts
  src/utils/common/openNewTab.ts
Labels: bug

#146 🐛 Fix: 로그인 새창 후 닫기 및 새로고침
  src/screens/LoginAndRegister/AppleErrorCallback.tsx
  src/screens/LoginAndRegister/AppleLoginCallback.tsx
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
Labels: bug

#147 🐛 Fix: 로그인 후 새로고침
  src/utils/common/openNewTab.ts
Labels: bug

#148 🐛 Fix: 로그인 후 새로고침
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
  src/utils/LoginAndRegister/Login.ts
Labels: bug

#149 🐛 Fix: 구글 로그인 에러 메세지
  src/screens/LoginAndRegister/GoogleLoginCallback.tsx
Labels: bug
